export default {
  'pierre': require('./halow-100/Frankenstein-01.png'),
  'pierre-mini': require('./halow-mini/Frankenstein-01.png'),
  'phil': require('./halow-100/Extraterrestrial-01.png'),
  'phil-mini': require('./halow-mini/Extraterrestrial-01.png'),
  'dave': require('./halow-100/Dave-01.png'),
  'dave-mini': require('./halow-mini/Dave-01.png'),
  'antoine': require('./halow-100/Ghostface-01.png'),
  'antoine-mini': require('./halow-mini/Ghostface-01.png'),
  'hugo': require('./halow-100/Goomba-01.png'),
  'hugo-mini': require('./halow-mini/Goomba-01.png'),
  'ben': require('./halow-100/Guy Fawkes-01.png'),
  'ben-mini': require('./halow-mini/Guy Fawkes-01.png'),
  'math': require('./halow-100/Hannibal-01.png'),
  'math-mini': require('./halow-mini/Hannibal-01.png'),
  'arthur': require('./halow-100/Zombie-01.png'),
  'arthur-mini': require('./halow-mini/Zombie-01.png'),
  'cha': require('./halow-100/Witch-01.png'),
  'cha-mini': require('./halow-mini/Witch-01.png'),
  'adrien': require('./halow-100/Pennywise-01.png'),
  'adrien-mini': require('./halow-mini/Pennywise-01.png'),
  'octave': require('./halow-100/The Count-01.png'),
  'octave-mini': require('./halow-mini/The Count-01.png'),
  'anouck': require('./halow-100/Jake Sulley-01.png'),
  'anouck-mini': require('./halow-mini/Jake Sulley-01.png'),
  'mel': require('./halow-100/Harley-01.png'),
  'mel-mini': require('./halow-mini/Harley-01.png'),
  'romain': require('./halow-100/Skull-01.png'),
  'romain-mini': require('./halow-mini/Skull-01.png'),
  'tom': require('./halow-100/Capt Spaulding-01.png'),
  'tom-mini': require('./halow-mini/Capt Spaulding-01.png'),
  'morgane': require('./halow-100/Chuckie-01.png'),
  'morgane-mini': require('./halow-mini/Chuckie-01.png'),
  'nina': require('./halow-100/Paul-01.png'),
  'nina-mini': require('./halow-mini/Paul-01.png'),
  'chris': require('./halow-100/Pinhead-01.png'),
  'chris-mini': require('./halow-mini/Pinhead-01.png'),
  'yann': require('./halow-100/Bat-01.png'),
  'yann-mini': require('./halow-mini/Bat-01.png'),
  'aline': require('./halow-100/Oompa Loompa-01.png'),
  'aline-mini': require('./halow-mini/Oompa Loompa-01.png'),
  'leo': require('./halow-100/Mike-01.png'),
  'leo-mini': require('./halow-mini/Mike-01.png'),
  'yoana': require('./halow-100/Devil-01.png'),
  'yoana-mini': require('./halow-mini/Devil-01.png'),
  'crown-100': require('./crown-100.png')
}
