export default {
  'pierre': require('./images/halow/Frankenstein-01.png'),
  'pierre-mini': require('./images/halow-mini/Frankenstein-01.png'),
  'phil': require('./images/halow/Extraterrestrial-01.png'),
  'phil-mini': require('./images/halow-mini/Extraterrestrial-01.png'),
  'dave': require('./images/halow/Dave-01.png'),
  'dave-mini': require('./images/halow-mini/Dave-01.png'),
  'antoine': require('./images/halow/Ghostface-01.png'),
  'antoine-mini': require('./images/halow-mini/Ghostface-01.png'),
  'hugo': require('./images/halow/Goomba-01.png'),
  'hugo-mini': require('./images/halow-mini/Goomba-01.png'),
  'ben': require('./images/halow/Guy Fawkes-01.png'),
  'ben-mini': require('./images/halow-mini/Guy Fawkes-01.png'),
  'math': require('./images/halow/Hannibal-01.png'),
  'math-mini': require('./images/halow-mini/Hannibal-01.png'),
  'arthur': require('./images/halow/Zombie-01.png'),
  'arthur-mini': require('./images/halow-mini/Zombie-01.png'),
  'cha': require('./images/halow/Witch-01.png'),
  'cha-mini': require('./images/halow-mini/Witch-01.png'),
  'adrien': require('./images/halow/Pennywise-01.png'),
  'adrien-mini': require('./images/halow-mini/Pennywise-01.png'),
  'octave': require('./images/halow/The Count-01.png'),
  'octave-mini': require('./images/halow-mini/The Count-01.png'),
  'anouck': require('./images/halow/Jake Sulley-01.png'),
  'anouck-mini': require('./images/halow-mini/Jake Sulley-01.png'),
}
